[2024-04-29T09:25:29.926+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T09:25:29.941+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.open_weather_sensor scheduled__2024-04-29T06:06:00+00:00 [queued]>
[2024-04-29T09:25:29.949+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.open_weather_sensor scheduled__2024-04-29T06:06:00+00:00 [queued]>
[2024-04-29T09:25:29.950+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T09:25:29.968+0000] {taskinstance.py:2327} INFO - Executing <Task(HttpSensor): open_weather_sensor> on 2024-04-29 06:06:00+00:00
[2024-04-29T09:25:29.976+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2304) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T09:25:29.978+0000] {standard_task_runner.py:63} INFO - Started process 2326 to run task
[2024-04-29T09:25:29.978+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'open_weather_sensor', 'scheduled__2024-04-29T06:06:00+00:00', '--job-id', '603', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmpm0qoadg5']
[2024-04-29T09:25:29.979+0000] {standard_task_runner.py:91} INFO - Job 603: Subtask open_weather_sensor
[2024-04-29T09:25:30.015+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.open_weather_sensor scheduled__2024-04-29T06:06:00+00:00 [running]> on host ce94facc171a
[2024-04-29T09:25:30.104+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='open_weather_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T06:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T06:06:00+00:00'
[2024-04-29T09:25:30.105+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T09:25:30.106+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-04-29T09:25:30.106+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Baku&APPID=682dec93d925536760749155cc3096bd
[2024-04-29T09:25:30.114+0000] {base.py:84} INFO - Using connection ID 'weather_id' for task execution.
[2024-04-29T09:25:30.514+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-04-29T09:25:30.515+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T09:25:30.526+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_open_weather, task_id=open_weather_sensor, execution_date=20240429T060600, start_date=20240429T092529, end_date=20240429T092530
[2024-04-29T09:25:30.558+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T09:25:30.615+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-29T09:25:30.621+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
