[2024-04-29T09:26:29.073+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T09:26:29.096+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.open_weather_sensor scheduled__2024-04-29T08:52:00+00:00 [queued]>
[2024-04-29T09:26:29.109+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.open_weather_sensor scheduled__2024-04-29T08:52:00+00:00 [queued]>
[2024-04-29T09:26:29.110+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T09:26:29.130+0000] {taskinstance.py:2327} INFO - Executing <Task(HttpSensor): open_weather_sensor> on 2024-04-29 08:52:00+00:00
[2024-04-29T09:26:29.143+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3043) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T09:26:29.144+0000] {standard_task_runner.py:63} INFO - Started process 3073 to run task
[2024-04-29T09:26:29.145+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'open_weather_sensor', 'scheduled__2024-04-29T08:52:00+00:00', '--job-id', '845', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmp3ed4jo6x']
[2024-04-29T09:26:29.147+0000] {standard_task_runner.py:91} INFO - Job 845: Subtask open_weather_sensor
[2024-04-29T09:26:29.208+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.open_weather_sensor scheduled__2024-04-29T08:52:00+00:00 [running]> on host ce94facc171a
[2024-04-29T09:26:29.316+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='open_weather_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T08:52:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T08:52:00+00:00'
[2024-04-29T09:26:29.318+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T09:26:29.318+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-04-29T09:26:29.319+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Baku&APPID=682dec93d925536760749155cc3096bd
[2024-04-29T09:26:29.330+0000] {base.py:84} INFO - Using connection ID 'weather_id' for task execution.
[2024-04-29T09:26:29.706+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-04-29T09:26:29.707+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T09:26:29.717+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_open_weather, task_id=open_weather_sensor, execution_date=20240429T085200, start_date=20240429T092629, end_date=20240429T092629
[2024-04-29T09:26:29.810+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T09:26:29.849+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-29T09:26:29.858+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
