[2024-04-29T09:32:04.983+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T09:32:04.995+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.run_etl scheduled__2024-04-29T09:30:00+00:00 [queued]>
[2024-04-29T09:32:05.002+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.run_etl scheduled__2024-04-29T09:30:00+00:00 [queued]>
[2024-04-29T09:32:05.003+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T09:32:05.014+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): run_etl> on 2024-04-29 09:30:00+00:00
[2024-04-29T09:32:05.019+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3359) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T09:32:05.021+0000] {standard_task_runner.py:63} INFO - Started process 3361 to run task
[2024-04-29T09:32:05.021+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'run_etl', 'scheduled__2024-04-29T09:30:00+00:00', '--job-id', '924', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmpv66ta802']
[2024-04-29T09:32:05.022+0000] {standard_task_runner.py:91} INFO - Job 924: Subtask run_etl
[2024-04-29T09:32:05.056+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.run_etl scheduled__2024-04-29T09:30:00+00:00 [running]> on host ce94facc171a
[2024-04-29T09:32:05.119+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T09:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T09:30:00+00:00'
[2024-04-29T09:32:05.120+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T09:32:05.135+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-29T09:32:05.136+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T09:32:05.142+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_open_weather, task_id=run_etl, execution_date=20240429T093000, start_date=20240429T093204, end_date=20240429T093205
[2024-04-29T09:32:05.154+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T09:32:05.165+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T09:32:05.167+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
