[2024-04-29T09:13:25.364+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T09:13:25.381+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.open_weather_sensor scheduled__2024-04-29T00:48:00+00:00 [queued]>
[2024-04-29T09:13:25.390+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.open_weather_sensor scheduled__2024-04-29T00:48:00+00:00 [queued]>
[2024-04-29T09:13:25.390+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T09:13:25.403+0000] {taskinstance.py:2327} INFO - Executing <Task(HttpSensor): open_weather_sensor> on 2024-04-29 00:48:00+00:00
[2024-04-29T09:13:25.411+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=509) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T09:13:25.412+0000] {standard_task_runner.py:63} INFO - Started process 531 to run task
[2024-04-29T09:13:25.412+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'open_weather_sensor', 'scheduled__2024-04-29T00:48:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmp82bbbp52']
[2024-04-29T09:13:25.413+0000] {standard_task_runner.py:91} INFO - Job 59: Subtask open_weather_sensor
[2024-04-29T09:13:25.458+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.open_weather_sensor scheduled__2024-04-29T00:48:00+00:00 [running]> on host ce94facc171a
[2024-04-29T09:13:25.557+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='open_weather_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T00:48:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T00:48:00+00:00'
[2024-04-29T09:13:25.561+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T09:13:25.562+0000] {baseoperator.py:399} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-04-29T09:13:25.562+0000] {http.py:137} INFO - Poking: /data/2.5/weather?q=Baku&APPID=682dec93d925536760749155cc3096bd
[2024-04-29T09:13:25.570+0000] {base.py:84} INFO - Using connection ID 'weather_id' for task execution.
[2024-04-29T09:13:25.979+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-04-29T09:13:25.980+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T09:13:25.991+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_open_weather, task_id=open_weather_sensor, execution_date=20240429T004800, start_date=20240429T091325, end_date=20240429T091325
[2024-04-29T09:13:26.028+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T09:13:26.063+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-29T09:13:26.067+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
