[2024-04-29T07:33:29.665+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T07:33:29.689+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T07:02:00+00:00 [queued]>
[2024-04-29T07:33:29.705+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T07:02:00+00:00 [queued]>
[2024-04-29T07:33:29.706+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T07:33:29.814+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-04-29 07:02:00+00:00
[2024-04-29T07:33:29.823+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2884) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T07:33:29.825+0000] {standard_task_runner.py:63} INFO - Started process 2915 to run task
[2024-04-29T07:33:29.830+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'transform_load_weather_data', 'scheduled__2024-04-29T07:02:00+00:00', '--job-id', '788', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmpr10vpurr']
[2024-04-29T07:33:29.833+0000] {standard_task_runner.py:91} INFO - Job 788: Subtask transform_load_weather_data
[2024-04-29T07:33:29.900+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T07:02:00+00:00 [running]> on host 6dbc7f679521
[2024-04-29T07:33:30.032+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T07:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T07:02:00+00:00'
[2024-04-29T07:33:30.034+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T07:33:30.062+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-29T07:33:30.062+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T07:33:30.078+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_open_weather, task_id=transform_load_weather_data, execution_date=20240429T070200, start_date=20240429T073329, end_date=20240429T073330
[2024-04-29T07:33:30.122+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T07:33:30.141+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T07:33:30.144+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
