[2024-04-29T07:32:54.431+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T07:32:54.451+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T05:20:00+00:00 [queued]>
[2024-04-29T07:32:54.462+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T05:20:00+00:00 [queued]>
[2024-04-29T07:32:54.463+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-29T07:32:54.480+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-04-29 05:20:00+00:00
[2024-04-29T07:32:54.489+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2444) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T07:32:54.490+0000] {standard_task_runner.py:63} INFO - Started process 2467 to run task
[2024-04-29T07:32:54.490+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_for_open_weather', 'transform_load_weather_data', 'scheduled__2024-04-29T05:20:00+00:00', '--job-id', '644', '--raw', '--subdir', 'DAGS_FOLDER/open_weather.py', '--cfg-path', '/tmp/tmp9g676zl1']
[2024-04-29T07:32:54.491+0000] {standard_task_runner.py:91} INFO - Job 644: Subtask transform_load_weather_data
[2024-04-29T07:32:54.531+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_for_open_weather.transform_load_weather_data scheduled__2024-04-29T05:20:00+00:00 [running]> on host 6dbc7f679521
[2024-04-29T07:32:54.629+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_for_open_weather' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T05:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-29T05:20:00+00:00'
[2024-04-29T07:32:54.631+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T07:32:54.659+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-29T07:32:54.659+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T07:32:54.671+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_for_open_weather, task_id=transform_load_weather_data, execution_date=20240429T052000, start_date=20240429T073254, end_date=20240429T073254
[2024-04-29T07:32:54.744+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T07:32:54.763+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T07:32:54.770+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
